// <auto-generated>
//     Generated from infra/auth0/permissions.json by scripts/generate-permissions.mjs.
//     Edit the manifest and re-run the script; changes made here are lost.
// </auto-generated>

using Microsoft.AspNetCore.Authorization;

namespace NpAspire.Api.Authorization;

/// <summary>
/// Permissions granted by Auth0 RBAC. The API authorizes on these names, never on role names, so roles can be
/// changed in Auth0 without touching the code.
/// </summary>
public static class Permissions
{
    /// <summary>Access-token claim Auth0 puts the caller's permissions in.</summary>
    public const string ClaimName = "permissions";

    /// <summary>Read your own profile</summary>
    public const string ReadProfile = "read:profile";

    /// <summary>Update your own profile</summary>
    public const string UpdateProfile = "update:profile";

    /// <summary>Read any user's profile</summary>
    public const string ReadUsers = "read:users";

    /// <summary>Every permission, in manifest order.</summary>
    public static readonly string[] All =
    [
        ReadProfile,
        UpdateProfile,
        ReadUsers,
    ];

    /// <summary>Adds one authorization policy per permission, named after the permission.</summary>
    public static AuthorizationBuilder AddPermissionPolicies(this AuthorizationBuilder builder)
    {
        builder.AddPolicy(ReadProfile, policy => policy.RequireClaim(ClaimName, ReadProfile));
        builder.AddPolicy(UpdateProfile, policy => policy.RequireClaim(ClaimName, UpdateProfile));
        builder.AddPolicy(ReadUsers, policy => policy.RequireClaim(ClaimName, ReadUsers));

        return builder;
    }
}
